### ISSUE TITLE
undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by gargsakshi7** [bjherger/ResumeParser#19]
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    import spacy
  File "/user/.conda/envs/resume/lib/python2.7/site-packages/spacy/__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "/user/.conda/envs/resume/lib/python2.7/site-packages/spacy/deprecated.py", line 8, in <module>
    from .cli import download
  File "/user/.conda/envs/resume/lib/python2.7/site-packages/spacy/cli/__init__.py", line 5, in <module>
    from .train import train, train_config
  File "/user/.conda/envs/resume/lib/python2.7/site-packages/spacy/cli/train.py", line 8, in <module>
    from ..scorer import Scorer
  File "/user/.conda/envs/resume/lib/python2.7/site-packages/spacy/scorer.py", line 4, in <module>
    from .gold import tags_to_entities
  File "spacy/morphology.pxd", line 25, in init spacy.gold (spacy/gold.cpp:23505)
  File "spacy/vocab.pxd", line 27, in init spacy.morphology (spacy/morphology.cpp:10713)
  File ".env/lib/python2.7/site-packages/preshed/counter.pxd", line 13, in init spacy.vocab (spacy/vocab.cpp:19474)
ImportError: /user/.local/lib/python2.7/site-packages/preshed/counter.so: undefined symbol: PyFPE_jbuf

**Comment by bjherger** [comment]
@gargsakshi7 Thanks for reaching out, and for the traceback. 

I don't think the issue you're having is with the software I've written, but rather with how you've installed numpy. Please check out this [so](https://stackoverflow.com/questions/36190757/numpy-undefined-symbol-pyfpe-jbuf) for help, but unfortunately I can't provide support for Numpy issues.
