### ISSUE TITLE
WindowsError when launching for first time

### ISSUE THREAD

**Issue by AdamLouly** [bjherger/ResumeParser#34]
C:\Users\Acer\Anaconda3\envs\myenv\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
INFO:root:Begin extract
C:\Users\Acer\Documents\PFE\ResumeParser\bin\lib.py:25: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  CONFS = yaml.load(open(confs_path))
INFO:root:Found 5 candidate files
INFO:root:Subset candidate files to extensions w/ available parsers. 5 files remain
Traceback (most recent call last):
  File "main.py", line 111, in <module>
    main()
  File "main.py", line 33, in main
    observations = extract()
  File "main.py", line 68, in extract
    observations['text'] = observations['file_path'].apply(lib.convert_pdf)
  File "C:\Users\Acer\Anaconda3\envs\myenv\lib\site-packages\pandas\core\series.py", line 3591, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2217, in pandas._libs.lib.map_infer
  File "C:\Users\Acer\Documents\PFE\ResumeParser\bin\lib.py", line 130, in convert_pdf
    stdout=subprocess.PIPE, stderr=subprocess.PIPE,
  File "C:\Users\Acer\Anaconda3\envs\myenv\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Users\Acer\Anaconda3\envs\myenv\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application

Getting this error when launching the main.py ..

**Comment by bjherger** [comment]
Great catch! WIP

**Comment by bjherger** [comment]
@AdamLouly This issue should be addressed by #35 . Please try now, and let me know if it works for you.

**Comment by AdamLouly** [comment]
@bjherger no longer the error thanks for fixing it :D

**Comment by bjherger** [comment]
Thanks for reporting it!
