### ISSUE TITLE
Unicode Decoding Error

### ISSUE THREAD

**Issue by gpavanb-osi** [bjherger/ResumeParser#45]
Hi

I am getting the following error when trying out the code on a resume in English.

**Error**
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 481: character maps to <undefined>

**Traceback**
Traceback (most recent call last):
  File "main.py", line 116, in <module>
    main()
  File "main.py", line 33, in main
    observations = extract()
  File "main.py", line 68, in extract
    observations['text'] = observations['file_path'].apply(lib.convert_pdf)
  File "C:\Users\pgovindaraju\Desktop\Python_Projects\Talent-Acquisition\venv\lib\site-packages\pandas\core\series.py", line 3591, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas\_libs\lib.pyx", line 2217, in pandas._libs.lib.map_infer
  File "C:\Users\pgovindaraju\Desktop\Python_Projects\Talent-Acquisition\ResumeParser\bin\lib.py", line 140, in convert_pdf
    return open(output_filepath).read()
  File "C:\Users\pgovindaraju\Desktop\Python_Projects\Talent-Acquisition\venv\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 481: character maps to <undefined>

**Comment by MinaTahaei** [comment]
same issue

**Comment by cuipengfeily** [comment]
same issue
