### ISSUE TITLE
python main.py thowing errors

### ISSUE THREAD

**Issue by lanceharvie** [bjherger/ResumeParser#50]
python main.py
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    from bin import field_extraction
  File "/home/lance/Downloads/ResumeParser-master/bin/field_extraction.py", line 3, in <module>
    from gensim.utils import simple_preprocess
  File "/home/lance/.local/lib/python2.7/site-packages/gensim/__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "/home/lance/.local/lib/python2.7/site-packages/gensim/parsing/__init__.py", line 4, in <module>
    from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2,  # noqa:F401
  File "/home/lance/.local/lib/python2.7/site-packages/gensim/parsing/preprocessing.py", line 42, in <module>
    from gensim import utils
  File "/home/lance/.local/lib/python2.7/site-packages/gensim/utils.py", line 45, in <module>
    from smart_open import smart_open
  File "/home/lance/.local/lib/python2.7/site-packages/smart_open/__init__.py", line 28, in <module>
    from .smart_open_lib import open, parse_uri, smart_open, register_compressor
  File "/home/lance/.local/lib/python2.7/site-packages/smart_open/smart_open_lib.py", line 24, in <module>
    import urllib.parse
ImportError: No module named parse

**Comment by zzdark** [comment]
sorry have you tried pip install parse
